server:
  port: 12000
spring:
  application:
    name: IT-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/traeric/ITConfigRepo.git
  rabbitmq:
    host: 192.168.43.228
management:   # 暴露触发消息总线的地址
  endpoint:
    web:
      exposure:
        include: bus-refresh
